/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/P4D2lJVKCZl
 */
import Image from "next/image";
import Link from "next/link";
import logo from "../../public/logo.png";
import Screenshot from "../../public/screenshot.png";

export default function Home() {
    return (
        <div className="flex flex-col min-h-screen">
            <header className="px-4 lg:px-6 h-14 flex items-center">
                <Link className="flex items-center justify-center" href="#">
                    <svg
                        xmlns="http://www.w3.org/2000/svg"
                        width="24"
                        height="24"
                        viewBox="0 0 24 24"
                        fill="none"
                        stroke="currentColor"
                        strokeWidth="2"
                        strokeLinecap="round"
                        strokeLinejoin="round"
                        className="h-6 w-6"
                    >
                        <rect width="14" height="8" x="5" y="2" rx="2" />
                        <rect width="20" height="8" x="2" y="14" rx="2" />
                        <path d="M6 18h2" />
                        <path d="M12 18h6" />
                    </svg>
                    <span className="ml-2 text-lg font-semibold">Journz</span>
                </Link>
            </header>
            <main className="flex-1">
                <section className="w-full py-6 md:py-12 lg:py-24 xl:py-32">
                    <div className="container px-4 md:px-6">
                        <div className="flex flex-col items-center space-y-4 text-center">
                            <Image
                                src={logo}
                                alt="Workday Tracker logo"
                                width={250}
                                height={250}
                                priority
                                className="rounded-full"
                            />
                            <div className="space-y-2">
                                <h1 className="text-3xl font-bold tracking-tighter sm:text-4xl md:text-5xl lg:text-6xl/none">
                                    Welcome to Journz
                                </h1>
                                <p className="mx-auto max-w-[700px] text-gray-500 md:text-xl dark:text-gray-400">
                                    A simple and effective tool to track your
                                    office days. Get daily reminders and monthly
                                    summaries.
                                </p>
                            </div>
                        </div>
                    </div>
                </section>
                <section className="w-full py-12 md:py-24 lg:py-32 bg-gray-100 dark:bg-gray-800">
                    <div className="container px-4 md:px-6 flex flex-col md:flex-row gap-10">
                        <div className="flex flex-col justify-center space-y-4 flex-1">
                            <div className="space-y-2">
                                <h2 className="text-3xl font-bold tracking-tighter sm:text-5xl">
                                    How it works
                                </h2>
                                <p className="max-w-[600px] text-gray-500 md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed dark:text-gray-400">
                                    {`Every workday, you'll receive an email
                                    asking "Are you going to the office today?".
                                    Simply reply with a "Yes" or "No". At the
                                    end of each month, you'll receive a summary
                                    of your office days.`}
                                </p>
                            </div>
                            <div className="flex flex-col gap-2 min-[400px]:flex-row ">
                                <Link
                                    className="inline-flex h-10 items-center justify-center rounded-md bg-gray-900 px-8 text-sm font-medium text-gray-50 shadow transition-colors hover:bg-gray-900/90 focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-gray-950 disabled:pointer-events-none disabled:opacity-50 dark:bg-gray-50 dark:text-gray-900 dark:hover:bg-gray-50/90 dark:focus-visible:ring-gray-300"
                                    href="#"
                                >
                                    Sign Up
                                </Link>
                            </div>
                        </div>
                        <div className="flex justify-center flex-1">
                            <Image
                                className="shadow-2xl rounded-xl"
                                src={Screenshot}
                                alt="Screenshot of Journz"
                                width={500}
                                height={500}
                            />
                        </div>
                    </div>
                </section>
            </main>
            <footer className="flex flex-col gap-2 sm:flex-row py-6 w-full shrink-0 items-center px-4 md:px-6 border-t">
                <p className="text-xs text-gray-500 dark:text-gray-400">
                    © 2024 Workday Tracker. All rights reserved.
                </p>
                <nav className="sm:ml-auto flex gap-4 sm:gap-6">
                    <Link
                        className="text-xs hover:underline underline-offset-4"
                        href="#"
                    >
                        Privacy Policy
                    </Link>
                    <Link
                        className="text-xs hover:underline underline-offset-4"
                        href="#"
                    >
                        Terms of Service
                    </Link>
                    <Link
                        className="text-xs hover:underline underline-offset-4"
                        href="#"
                    >
                        Contact
                    </Link>
                </nav>
            </footer>
        </div>
    );
}
